version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env/.env.prod-sample
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d   
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db-sample
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
